USE ROLE KAFKA_CONNECTOR_ROLE;

CREATE TASK IF NOT EXISTS CRYPTO_PIPELINE.RAW.TASK_TRANSFORM_CRYPTO
    WAREHOUSE = CRYPTO_WH
    SCHEDULE = '5 MINUTE'
AS
INSERT INTO CRYPTO_PIPELINE.RAW.CRYPTO_PRICES_ENRICHED (
    ID, SYMBOL, NAME, CURRENT_PRICE, MARKET_CAP, MARKET_CAP_RANK,
    TOTAL_VOLUME, HIGH_24H, LOW_24H, PRICE_CHANGE_24H, PRICE_CHANGE_PCT_24H,
    CIRCULATING_SUPPLY, MAX_SUPPLY, ATH, ATH_DATE, LAST_UPDATED, INGESTED_AT
)
SELECT
    ID::STRING,
    SYMBOL::STRING,
    NAME::STRING,
    CURRENT_PRICE::FLOAT,
    MARKET_CAP::NUMBER,
    MARKET_CAP_RANK::INT,
    TOTAL_VOLUME::NUMBER,
    HIGH_24H::FLOAT,
    LOW_24H::FLOAT,
    PRICE_CHANGE_24H::FLOAT,
    PRICE_CHANGE_PCT_24H::FLOAT,
    CIRCULATING_SUPPLY::FLOAT,
    MAX_SUPPLY::FLOAT,
    ATH::FLOAT,
    ATH_DATE::STRING,
    LAST_UPDATED::TIMESTAMP_TZ,
    INGESTED_AT::TIMESTAMP_TZ
FROM CRYPTO_PIPELINE.RAW.STREAM_CRYPTO_PRICES
WHERE METADATA$ACTION = 'INSERT';

ALTER TASK CRYPTO_PIPELINE.RAW.TASK_TRANSFORM_CRYPTO RESUME;