USE ROLE KAFKA_CONNECTOR_ROLE;

CREATE TABLE IF NOT EXISTS CRYPTO_PIPELINE.RAW.CRYPTO_PRICES_ENRICHED (
    ID                   STRING,
    SYMBOL               STRING,
    NAME                 STRING,
    CURRENT_PRICE        FLOAT,
    MARKET_CAP           NUMBER,
    MARKET_CAP_RANK      INT,
    TOTAL_VOLUME         NUMBER,
    HIGH_24H             FLOAT,
    LOW_24H              FLOAT,
    PRICE_CHANGE_24H     FLOAT,
    PRICE_CHANGE_PCT_24H FLOAT,
    CIRCULATING_SUPPLY   FLOAT,
    MAX_SUPPLY           FLOAT,
    ATH                  FLOAT,
    ATH_DATE             STRING,
    LAST_UPDATED         TIMESTAMP_TZ,
    INGESTED_AT          TIMESTAMP_TZ,
    PROCESSED_AT         TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);